
import Link from 'next/link'
import './globals.css'



export const metadata = {
  title: 'Pocketmon Project',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <div>
          <Link href="/">homepage</Link>
          <Link href="/list">List</Link>
        </div>
        {children}</body>
    </html>
  )
}
