import Link from 'next/link'
import './globals.css'
import Header from '@/components/header'

export const metadata = {
  title: 'Pocketmon Project',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html>
     
      <body >
      <Header/>
        {children}
      </body>
    </html>
  )
}
